version: '3.1'

volumes:
  wordpress:
  db:

networks:
  word_net:
    driver: bridge

services:
  wordpress:
    image: wordpress:latest 
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: dbword 
      WORDPRESS_DB_USER: userdb 
      WORDPRESS_DB_PASSWORD: userpass 
      WORDPRESS_DB_NAME: db
    volumes:
      - wordpress:/var/www/html
    networks:
      - word_net

  db:
    image: mysql:5.7
    restart: always
    container_name: dbword 
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: userdb 
      MYSQL_PASSWORD: userpass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - word_net

